//--------------------------------------------------------
// ORHVcRIOController
// Created by Mark  A. Howe on Oct 17, 2017
// Code partially generated by the OrcaCodeWizard. Written by Mark A. Howe.
// Copyright (c) 2017, University of North Carolina. All rights reserved.
//-----------------------------------------------------------
//This program was prepared for the Regents of the University of
//North Carolina sponsored in part by the United States
//Department of Energy (DOE) under Grant #DE-FG02-97ER41020.
//The University has certain rights in the program pursuant to
//the contract and the program should not be copied or distributed
//outside your organization.  The DOE and the University of
//North Carolina reserve all rights in the program. Neither the authors,
//University of North Carolina, or U.S. Government make any warranty,
//express or implied, or assume any liability or responsibility
//for the use of this software.
//-------------------------------------------------------------

#pragma mark ***Imported Files
@class ORValueBarGroupView;

@interface ORHVcRIOController : OrcaObjectController
{
	IBOutlet NSTextField*	ipConnectedTextField;
	IBOutlet NSTextField*	ipAddressTextField;
	IBOutlet NSButton*		ipConnectButton;

	IBOutlet NSTextField*   setPointFileField;
	IBOutlet NSTextField*	cmdQueCountField;
    IBOutlet NSButton*      lockButton;

    IBOutlet NSButton*      writeAllSetPointsButton;
		
	IBOutlet NSButton*		readSetPointFileButton;
	IBOutlet NSButton*		writeSetPointFileButton;
    IBOutlet NSButton*      readPostRegulationButton;

	IBOutlet NSTableView*	setPointTableView;
    IBOutlet NSTableView*   measuredValueTableView;
    IBOutlet NSTableView*   postRegulationTableView;
    IBOutlet NSButton*      addPostRegulationPointButton;
    IBOutlet NSButton*      removePostRegulationPointButton;
    IBOutlet NSTextField*   postRegulationFileField;
    
    IBOutlet NSTextField* expertPCControlOnlyField;
    IBOutlet NSTextField* zeusHasControlField;
    IBOutlet NSTextField* orcaHasControlField;
    IBOutlet NSPopUpButton* pollTimePU;
    IBOutlet NSProgressIndicator* progressWheel;
    
    IBOutlet ORValueBarGroupView*  queueValueBar;
    IBOutlet NSButton*    verboseCB;
    IBOutlet NSButton*    showFormattedDatesCB;
    
    IBOutlet NSBox* mainSpecBox;
    IBOutlet NSBox* preSpecBox;
    IBOutlet NSTextField* retardingPotentialTextField;
    IBOutlet NSTextField* targetPotentialTextField;
    IBOutlet NSTextField* postRegTextField;
    IBOutlet NSTextField* pollTimeTextField;
    IBOutlet NSTextField* mainSpecVoltageTextField;
    IBOutlet NSTextField* mainSpecPostRegVoltageTextField;
    IBOutlet NSTextField* ieCommonTextField;
    IBOutlet NSTextField* preSpecVoltageTextField;
    IBOutlet NSTextField* westConeTextField;
    IBOutlet NSTextField* eastConeTextField;
    IBOutlet NSTextField* southConeTextField;
    IBOutlet NSTextField* northConeTextField;
    IBOutlet NSTextField* wireElectrodeTextField;
    IBOutlet NSTextField* setMainSpecVoltageTextField;
    IBOutlet NSTextField* setIeCommonTextField;
    IBOutlet NSTextField* setEwSteepConeTextField;
    IBOutlet NSTextField* setPreSpecVoltageTextField;
    IBOutlet NSTextField* setSouthConeTextField;
    IBOutlet NSTextField* setNorthConeTextField;
    IBOutlet NSTextField* setWireElectrodeTextField;
    IBOutlet NSTextField* mainSpecStatusTextField;
    IBOutlet NSButton* setMainSpecVoltageButton;
    IBOutlet NSButton* setIECommonButton;
    IBOutlet NSButton* setEWSteepConesButton;
    IBOutlet NSButton* setPreSpecVoltageButton;
    IBOutlet NSButton* setSouthConeButton;
    IBOutlet NSButton* setNorthConeButton;
    IBOutlet NSButton* setWireElectrodeButton;
    IBOutlet NSButton* enablePostRegButton;
    IBOutlet NSButton* enablePostRegAPRButton;
    IBOutlet NSButton* mainSpecStopRampButton;
    IBOutlet NSButton* mainSpecOffButton;
    IBOutlet NSButton* postRegOffButton;
    IBOutlet NSButton* preSpecOffButton;
    IBOutlet NSPanel* confirmMainSpecOffPanel;
    IBOutlet NSButton* confirmMainSpecOffButton;
    IBOutlet NSButton* cancelMainSpecOffButton;
    IBOutlet NSPanel* confirmPostRegOffPanel;
    IBOutlet NSButton* confirmPostRegOffButton;
    IBOutlet NSButton* cancelPostRegOffButton;
    IBOutlet NSPanel* confirmPreSpecOffPanel;
    IBOutlet NSButton* confirmPreSpecOffButton;
    IBOutlet NSButton* cancelPreSpecOffButton;
    IBOutlet NSPanel* confirmPostRegVoltagePanel;
    IBOutlet NSButton* confirmPostRegVoltageButton;
    IBOutlet NSButton* cancelPostRegVoltageButton;
    IBOutlet NSPanel* confirmSAPModePanel;
    IBOutlet NSButton* confirmSAPModeButton;
    IBOutlet NSButton* cancelSAPModeButton;
    IBOutlet NSButton* sapModeButton;
    IBOutlet NSButton* currentSetPointButton;
    IBOutlet NSPopUpButton* postRegConfigPU;
    IBOutlet NSTextField* postRegPrecisionTextField;
    IBOutlet NSTextField* postRegAPRPrecisionTextField;
    IBOutlet NSTextField* postRegAPRTimeoutTextField;
    IBOutlet NSTextField* postRegDefSFTextField;
    IBOutlet NSTextField* vmScaleFactorTextField;
}

#pragma mark ***Initialization
- (id) init;
- (void) awakeFromNib;

#pragma mark ***Notifications
- (void) registerNotificationObservers;
- (void) updateWindow;

#pragma mark ***Interface Management
- (void) setPointChanged:(NSNotification*)aNote;
- (void) setPointsReadBackChanged:(NSNotification*)aNote;
- (void) lockChanged:(NSNotification*)aNote;
- (void) queCountChanged:(NSNotification*)aNote;
- (void) ipAddressChanged:(NSNotification*)aNote;
- (void) isConnectedChanged:(NSNotification*)aNote;
- (void) measuredValuesChanged:(NSNotification*)aNote;
- (void) verboseChanged:(NSNotification*)aNote;
- (void) pollTimeChanged:(NSNotification*)aNote;
- (void) setButtonStates;
- (void) postRegulationPointAdded:(NSNotification*)aNote;
- (void) postRegulationPointRemoved:(NSNotification*)aNote;
- (void) updatePostRegulationTable;
- (void) mainSpecRamping:(NSNotification*)aNote;
- (void) mainSpecPostRegRamping:(NSNotification*)aNote;
- (void) mainSpecPostRegAPRRamping:(NSNotification*)aNote;
- (void) mainSpecRampSuccess:(NSNotification*)aNote;
- (void) mainSpecRampFailure:(NSNotification*)aNote;
- (void) estimatingScaleFactor:(NSNotification*)aNote;
- (void) postRegPrecisionChanged:(NSNotification*)aNote;
- (void) postRegEnabledChanged:(NSNotification*)aNote;
- (void) postRegAPREnabledChanged:(NSNotification*)aNote;
- (void) postRegAPRPrecisionChanged:(NSNotification*)aNote;
- (void) postRegAPRTimeoutChanged:(NSNotification*)aNote;
- (void) postRegConfigChanged:(NSNotification*)aNote;
- (void) postRegDefSFChanged:(NSNotification*)aNote;
- (void) ieSAPModeChanged:(NSNotification*)aNote;
- (void) vmScaleFactorChanged:(NSNotification*)aNote;

#pragma mark ***Actions

//HVcRIO
- (IBAction) writeSetpointsAction:(id)sender;
- (IBAction) readBackSetpointsAction:(id)sender;
- (IBAction) pushReadBacksToSetPointsAction:(id)sender;
- (IBAction) readMeasuredValuesAction:(id)sender;
- (IBAction) lockAction:(id) sender;
- (IBAction) readSetPointFile:(id)sender;
- (IBAction) saveSetPointFile:(id)sender;
- (IBAction) ipAddressFieldAction:(id)sender;
- (IBAction) connectAction: (id) aSender;
- (IBAction) flushQueueAction: (id) aSender;
- (IBAction) verboseAction: (id) aSender;
- (IBAction) addPostRegulationPoint: (id) aSender;
- (IBAction) removePostRegulationPoint: (id) aSender;
- (IBAction) readPostRegulationScaleFactors: (id) aSender;
- (IBAction) savePostRegulationScaleFactors: (id) aSender;
- (IBAction) pollTimeAction: (id) aSender;
- (BOOL) tableView:(NSTableView *)tableView shouldSelectRow:(int)row;
- (IBAction) setMainSpecVoltageTextAction:(id)sender;
- (IBAction) setIeCommonTextAction:(id)sender;
- (IBAction) setEwSteepConeTextAction:(id)sender;
- (IBAction) setPreSpecVoltageTextAction:(id)sender;
- (IBAction) setSouthConeTextAction:(id)sender;
- (IBAction) setNorthConeTextAction:(id)sender;
- (IBAction) setWireElectrodeTextAction:(id)sender;
- (IBAction) setMainSpecVoltageAction:(id)sender;
- (IBAction) setIECommonAction:(id)sender;
- (IBAction) setEWSteepConesAction:(id)sender;
- (IBAction) setPreSpecVoltageAction:(id)sender;
- (IBAction) setSouthConeAction:(id)sender;
- (IBAction) setNorthConeAction:(id)sender;
- (IBAction) setWireElectrodeAction:(id)sender;
- (IBAction) mainSpecStopRampAction:(id)sender;
- (IBAction) mainSpecOffAction:(id)sender;
- (IBAction) mainSpecOffAction:(id)sender;
- (IBAction) confirmMainSpecOffAction:(id)sender;
- (IBAction) cancelMainSpecOffAction:(id)sender;
- (IBAction) postRegOffAction:(id)sender;
- (IBAction) confirmPostRegOffAction:(id)sender;
- (IBAction) cancelPostRegOffAction:(id)sender;
- (IBAction) confirmPostRegVoltageAction:(id)sender;
- (IBAction) cancelPostRegVoltageAction:(id)sender;
- (IBAction) confirmSAPModeAction:(id)sender;
- (IBAction) cancelSAPModeAction:(id)sender;
- (IBAction) sapModeAction:(id)sender;
- (IBAction) preSpecOffAction:(id)sender;
- (IBAction) confirmPreSpecOffAction:(id)sender;
- (IBAction) cancelPreSpecOffAction:(id)sender;
- (IBAction) currentSetPointAction:(id)sender;
- (IBAction) postRegConfigAction:(id)sender;
- (IBAction) postRegPrecisionAction:(id)sender;
- (IBAction) postRegEnabledAction:(id)sender;
- (IBAction) postRegAPREnabledAction:(id)sender;
- (IBAction) postRegAPRPrecisionAction:(id)sender;
- (IBAction) postRegAPRTimeoutAction:(id)sender;
- (IBAction) postRegDefSFAction:(id)sender;
- (IBAction) vmScaleFactorAction:(id)sender;

#pragma mark •••Convenience Methods
- (double) checkTFVoltage:(id)sender withMin:(double)minV andMax:(double)maxV;
- (double) checkVoltage:(double)voltage withMin:(double)minV andMax:(double)maxV;
- (void) changeButton:(NSButton*)button withColor:(NSColor*)color;
- (BOOL) checkButtonStatus:(NSButton*)button fromTextField:(NSTextField*)text
                withString:(NSString*)str withMin:(double)minv andMax:(double)maxv;
- (BOOL) checkButtonStatus:(NSButton*)button fromTextField:(NSTextField*)text withString:(NSString*)str;
- (void) checkButtonStatus;
- (void) currentSetPoints;

@end


